services:
  bitcoin:
    image: flarefoundation/bitcoin:29.0
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:18332:18332
      - ${BIND_IP}:18333:18333
    volumes:
      - bitcoin-testnet-data:/opt/bitcoin/.bitcoin/db
      - ./config-testnet/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  bitcoin-debug:
    image: debian:12
    pid: service:bitcoin
    network_mode: service:bitcoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - bitcoin
    profiles: 
      - debug

  litecoin:
    image: flarefoundation/litecoin:0.21.3
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:19332:19332
      - ${BIND_IP}:19333:19333
    volumes:
      - litecoin-testnet-data:/opt/litecoin/.litecoin/db
      - ./config-testnet/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  litecoin-debug:
    image: debian:12
    pid: service:litecoin
    network_mode: service:litecoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - litecoin
    profiles: 
      - debug

  dogecoin:
    image: flarefoundation/dogecoin:1.14.9
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:44555:44555
      - ${BIND_IP}:44556:44556
    volumes:
      - dogecoin-testnet-data:/opt/dogecoin/.dogecoin/db
      - ./config-testnet/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  dogecoin-debug:
    image: debian:12
    pid: service:dogecoin
    network_mode: service:dogecoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - dogecoin
    profiles: 
      - debug

  rippled:
    image: flarefoundation/rippled:2.4.0
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:15005:5005  # port_rpc_admin_local
      - ${BIND_IP}:16006:6006  # port_ws_admin_local
      - ${BIND_IP}:11235:51235 # port_peer
      - ${BIND_IP}:11234:51234 # port_rpc_public
      - ${BIND_IP}:11233:51233 # port_ws_public
      - ${BIND_IP}:10051:50051 # port_grpc
    volumes:
      - ripple-testnet-data:/opt/ripple/.ripple/db
      - ./config-testnet/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./config-testnet/ripple/validators.txt:/opt/ripple/.ripple/validators.txt

  rippled-debug:
    image: debian:12
    pid: service:rippled
    network_mode: service:rippled
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - rippled
    profiles: 
      - debug

  algorand:
    image: flarefoundation/algorand:4.1.2
    ports:
      - ${BIND_IP}:18080:8080
      - ${BIND_IP}:4161:4161
    environment:
      ALGOD_NETWORK: testnet
    volumes:
      - algorand-testnet-data:/opt/algorand/.algorand
      - ./config-testnet/algorand/config.json:/opt/algorand/.algorand/config.json
      - ./config-testnet/algorand/algod.token:/opt/algorand/.algorand/algod.token

  algorand-debug:
    image: debian:12
    pid: service:algorand
    network_mode: service:algorand
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - algorand
    profiles: 
      - debug

volumes:
  bitcoin-testnet-data:
  litecoin-testnet-data:
  dogecoin-testnet-data:
  ripple-testnet-data:
  algorand-testnet-data:
