services:
  bitcoin:
    image: flarefoundation/bitcoin:29.0
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:9332:9332
    volumes:
      - bitcoin-data:/opt/bitcoin/.bitcoin/db
      - ./config/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  bitcoin-debug:
    image: debian:12
    pid: service:bitcoin
    network_mode: service:bitcoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - bitcoin
    profiles: 
      - debug

  litecoin:
    image: flarefoundation/litecoin:0.21.3
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:8332:8332
    volumes:
      - litecoin-data:/opt/litecoin/.litecoin/db
      - ./config/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  litecoin-debug:
    image: debian:12
    pid: service:litecoin
    network_mode: service:litecoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - litecoin
    profiles: 
      - debug

  dogecoin:
    image: flarefoundation/dogecoin:1.14.9
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:7332:7332
    volumes:
      - dogecoin-data:/opt/dogecoin/.dogecoin/db
      - ./config/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  dogecoin-debug:
    image: debian:12
    pid: service:dogecoin
    network_mode: service:dogecoin
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - dogecoin
    profiles: 
      - debug

  rippled:
    image: flarefoundation/rippled:2.4.0
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:5005:5005   # port_rpc_admin_local
      - ${BIND_IP}:6006:6006   # port_ws_admin_local
      - ${BIND_IP}:51235:51235 # port_peer
      - ${BIND_IP}:51234:51234 # port_rpc_public
      - ${BIND_IP}:51233:51233 # port_ws_public
      - ${BIND_IP}:50051:50051 # port_grpc
    volumes:
      - ripple-data:/opt/ripple/.ripple/db
      - ./config/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./config/ripple/validators.txt:/opt/ripple/.ripple/validators.txt

  rippled-debug:
    image: debian:12
    pid: service:rippled
    network_mode: service:rippled
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - rippled
    profiles: 
      - debug

  algorand:
    image: flarefoundation/algorand:4.1.2
    ports:
      - ${BIND_IP}:6332:8080
      - ${BIND_IP}:4160:4160
      - ${BIND_IP}:9100:9100
    #environment:
      #ALGOD_TOKEN: changeitchangeitchangeitchangeitchangeitchangeitchangeitchangeit
    volumes:
      - algorand-data:/opt/algorand/.algorand
      - ./config/algorand/config.json:/opt/algorand/.algorand/config.json
      - ./config/algorand/algod.token:/opt/algorand/.algorand/algod.token

  algorand-debug:
    image: debian:12
    pid: service:algorand
    network_mode: service:algorand
    privileged: true
    command: |
      bash -c "
        apt-get update && 
        apt-get install -y curl jq netcat-openbsd tcpdump strace &&
        sleep infinity
      "
    depends_on:
      - algorand
    profiles: 
      - debug

volumes:
  bitcoin-data:
  litecoin-data:
  dogecoin-data:
  ripple-data:
  algorand-data:
